services:
  ldap:
    image: osixia/openldap:1.5.0
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    environment:
      LDAP_ORGANISATION: Openknowledge
      LDAP_DOMAIN: openknowledge.de
      LDAP_BASE_DN: dc=openknowledge,dc=de
    command: --copy-service

  service:
    image: ldap-showcase/ldap-service:0
    ports:
      - 8080:8080
    environment:
      LDAP_HOST: ldap
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=openknowledge,dc=de
      LDAP_BIND_DN: cn=admin,dc=openknowledge,dc=de
      LDAP_BIND_PASSWORD: admin
